### ISSUE TITLE
Gutenberg Blocks

### ISSUE THREAD

**Issue by Abelc01** [CodeCabin/sola-testimonials#11]

**Comment by DylanCodeCabin** [comment]
We need 2 blocks for the Basic:
- All testimonials (use shortcode)
- Single testimonial (use shortcode)

**Comment by DylanCodeCabin** [comment]
The original implementation was developed before the official gutenberg system was released to WP core. So we need to get rid of the existing stuff, and start from scratch, please. 

It is possible some of this may be salvaged but I recommend rebuilding this to ensure things are totally stable.
